version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:7.17.2
#    ports:
#      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - es_net
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
#  kibana:
#    image: kibana:7.17.2
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    networks:
#      - es_net
  backend:
    image: tgarchive-backend:latest
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - es_net
    depends_on:
      - elasticsearch
    volumes:
      - ./zipfiles:/data/zipfiles
  frontend:
    image: tgarchive-frontend:latest
    ports:
      - "80:80"
    networks:
      - es_net
    depends_on:
      - backend
networks:
  es_net:
    driver: bridge
volumes:
  es_data:
